CREATE DATABASE focus;

CREATE TABLE users(
    id SERIAL PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone bigInt NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);